from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(416, 428)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.txtOutputPath = QtGui.QLineEdit(Dialog)
        self.txtOutputPath.setObjectName(_fromUtf8("txtOutputPath"))
        self.gridLayout.addWidget(self.txtOutputPath, 1, 0, 1, 4)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.txtOutputFileNamePattern = QtGui.QLineEdit(Dialog)
        self.txtOutputFileNamePattern.setText(_fromUtf8(""))
        self.txtOutputFileNamePattern.setObjectName(_fromUtf8("txtOutputFileNamePattern"))
        self.gridLayout.addWidget(self.txtOutputFileNamePattern, 3, 0, 1, 4)
        self.chkCamelCase = QtGui.QCheckBox(Dialog)
        self.chkCamelCase.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkCamelCase.setObjectName(_fromUtf8("chkCamelCase"))
        self.gridLayout.addWidget(self.chkCamelCase, 4, 0, 1, 3)
        self.chkUseEightChars = QtGui.QCheckBox(Dialog)
        self.chkUseEightChars.setFocusPolicy(QtCore.Qt.NoFocus)
        self.chkUseEightChars.setObjectName(_fromUtf8("chkUseEightChars"))
        self.gridLayout.addWidget(self.chkUseEightChars, 5, 0, 1, 3)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.lblExample = QtGui.QLabel(Dialog)
        self.lblExample.setMinimumSize(QtCore.QSize(0, 50))
        self.lblExample.setText(_fromUtf8(""))
        self.lblExample.setWordWrap(True)
        self.lblExample.setObjectName(_fromUtf8("lblExample"))
        self.gridLayout.addWidget(self.lblExample, 7, 0, 1, 4)
        self.btnGenre = QtGui.QPushButton(Dialog)
        self.btnGenre.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnGenre.setObjectName(_fromUtf8("btnGenre"))
        self.gridLayout.addWidget(self.btnGenre, 8, 0, 1, 1)
        self.btnYear = QtGui.QPushButton(Dialog)
        self.btnYear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnYear.setObjectName(_fromUtf8("btnYear"))
        self.gridLayout.addWidget(self.btnYear, 8, 1, 1, 1)
        self.btnPublisher = QtGui.QPushButton(Dialog)
        self.btnPublisher.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPublisher.setObjectName(_fromUtf8("btnPublisher"))
        self.gridLayout.addWidget(self.btnPublisher, 8, 2, 1, 1)
        self.btnFormat_3 = QtGui.QPushButton(Dialog)
        self.btnFormat_3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnFormat_3.setObjectName(_fromUtf8("btnFormat_3"))
        self.gridLayout.addWidget(self.btnFormat_3, 8, 3, 1, 1)
        self.btnMachineType = QtGui.QPushButton(Dialog)
        self.btnMachineType.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnMachineType.setObjectName(_fromUtf8("btnMachineType"))
        self.gridLayout.addWidget(self.btnMachineType, 9, 0, 1, 1)
        self.btnLetter = QtGui.QPushButton(Dialog)
        self.btnLetter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnLetter.setObjectName(_fromUtf8("btnLetter"))
        self.gridLayout.addWidget(self.btnLetter, 9, 1, 1, 1)
        self.btnLanguage = QtGui.QPushButton(Dialog)
        self.btnLanguage.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnLanguage.setObjectName(_fromUtf8("btnLanguage"))
        self.gridLayout.addWidget(self.btnLanguage, 9, 2, 1, 1)
        self.btnSlash = QtGui.QPushButton(Dialog)
        self.btnSlash.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSlash.setObjectName(_fromUtf8("btnSlash"))
        self.gridLayout.addWidget(self.btnSlash, 9, 3, 1, 1)
        self.btnNumberOfPlayers = QtGui.QPushButton(Dialog)
        self.btnNumberOfPlayers.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnNumberOfPlayers.setObjectName(_fromUtf8("btnNumberOfPlayers"))
        self.gridLayout.addWidget(self.btnNumberOfPlayers, 10, 0, 1, 1)
        self.btnGameName = QtGui.QPushButton(Dialog)
        self.btnGameName.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnGameName.setObjectName(_fromUtf8("btnGameName"))
        self.gridLayout.addWidget(self.btnGameName, 10, 1, 1, 1)
        self.btnModFlags = QtGui.QPushButton(Dialog)
        self.btnModFlags.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnModFlags.setObjectName(_fromUtf8("btnModFlags"))
        self.gridLayout.addWidget(self.btnModFlags, 10, 2, 1, 1)
        self.btnHyphen = QtGui.QPushButton(Dialog)
        self.btnHyphen.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnHyphen.setObjectName(_fromUtf8("btnHyphen"))
        self.gridLayout.addWidget(self.btnHyphen, 10, 3, 1, 1)
        self.btnFormat = QtGui.QPushButton(Dialog)
        self.btnFormat.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnFormat.setObjectName(_fromUtf8("btnFormat"))
        self.gridLayout.addWidget(self.btnFormat, 11, 0, 1, 1)
        self.btnPart = QtGui.QPushButton(Dialog)
        self.btnPart.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnPart.setObjectName(_fromUtf8("btnPart"))
        self.gridLayout.addWidget(self.btnPart, 11, 1, 1, 1)
        self.btnSide = QtGui.QPushButton(Dialog)
        self.btnSide.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnSide.setObjectName(_fromUtf8("btnSide"))
        self.gridLayout.addWidget(self.btnSide, 11, 2, 1, 1)
        self.btnUnderscore = QtGui.QPushButton(Dialog)
        self.btnUnderscore.setFocusPolicy(QtCore.Qt.NoFocus)
        self.btnUnderscore.setObjectName(_fromUtf8("btnUnderscore"))
        self.gridLayout.addWidget(self.btnUnderscore, 11, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 12, 1, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Edit output folder structure", None))
        self.label.setText(_translate("Dialog", "Output folder structure pattern:", None))
        self.label_3.setText(_translate("Dialog", "Output file name pattern:", None))
        self.chkCamelCase.setText(_translate("Dialog", "CamelCaseInsteadOfSpaces", None))
        self.chkUseEightChars.setText(_translate("Dialog", "Use 8.3 naming scheme", None))
        self.label_2.setText(_translate("Dialog", "Example:", None))
        self.btnGenre.setText(_translate("Dialog", "{Genre}", None))
        self.btnYear.setText(_translate("Dialog", "{Year}", None))
        self.btnPublisher.setText(_translate("Dialog", "{Publisher}", None))
        self.btnFormat_3.setText(_translate("Dialog", "{ZXDB_ID}", None))
        self.btnMachineType.setText(_translate("Dialog", "{MachineType}", None))
        self.btnLetter.setText(_translate("Dialog", "{Letter}", None))
        self.btnLanguage.setText(_translate("Dialog", "{Language}", None))
        self.btnSlash.setText(_translate("Dialog", "Slash (\\)", None))
        self.btnNumberOfPlayers.setText(_translate("Dialog", "{MaxPlayers}", None))
        self.btnGameName.setText(_translate("Dialog", "{GameName}", None))
        self.btnModFlags.setText(_translate("Dialog", "{ModFlags}", None))
        self.btnHyphen.setText(_translate("Dialog", "Hyphen ( - )", None))
        self.btnFormat.setText(_translate("Dialog", "{Format}", None))
        self.btnPart.setText(_translate("Dialog", "{Part}", None))
        self.btnSide.setText(_translate("Dialog", "{Side}", None))
        self.btnUnderscore.setText(_translate("Dialog", "Underscore(_)", None))

