# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SorterLauncher.ui'
#
# Created: Sat Jan 27 23:55:42 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 550)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(500, 550))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setBaseSize(QtCore.QSize(0, 0))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pokemaster.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        Dialog.setSizeGripEnabled(False)
        self.gridLayout_3 = QtGui.QGridLayout(Dialog)
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnLoadSettings = QtGui.QPushButton(Dialog)
        self.btnLoadSettings.setObjectName(_fromUtf8("btnLoadSettings"))
        self.horizontalLayout.addWidget(self.btnLoadSettings)
        self.btnSaveSettings = QtGui.QPushButton(Dialog)
        self.btnSaveSettings.setObjectName(_fromUtf8("btnSaveSettings"))
        self.horizontalLayout.addWidget(self.btnSaveSettings)
        spacerItem = QtGui.QSpacerItem(158, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnSortFiles = QtGui.QPushButton(Dialog)
        self.btnSortFiles.setObjectName(_fromUtf8("btnSortFiles"))
        self.horizontalLayout.addWidget(self.btnSortFiles)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabMainOptions = QtGui.QWidget()
        self.tabMainOptions.setAccessibleName(_fromUtf8(""))
        self.tabMainOptions.setObjectName(_fromUtf8("tabMainOptions"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabMainOptions)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.tabMainOptions)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.btnAddPath = QtGui.QPushButton(self.groupBox)
        self.btnAddPath.setObjectName(_fromUtf8("btnAddPath"))
        self.gridLayout_2.addWidget(self.btnAddPath, 0, 1, 1, 1)
        self.chkTraverseSubdirectories = QtGui.QCheckBox(self.groupBox)
        self.chkTraverseSubdirectories.setChecked(True)
        self.chkTraverseSubdirectories.setObjectName(_fromUtf8("chkTraverseSubdirectories"))
        self.gridLayout_2.addWidget(self.chkTraverseSubdirectories, 3, 0, 1, 1)
        self.lstInputPaths = QtGui.QListWidget(self.groupBox)
        self.lstInputPaths.setObjectName(_fromUtf8("lstInputPaths"))
        self.gridLayout_2.addWidget(self.lstInputPaths, 0, 0, 3, 1)
        self.btnRemovePaths = QtGui.QPushButton(self.groupBox)
        self.btnRemovePaths.setObjectName(_fromUtf8("btnRemovePaths"))
        self.gridLayout_2.addWidget(self.btnRemovePaths, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.tabMainOptions)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.txtOutputPath = QtGui.QLineEdit(self.tabMainOptions)
        self.txtOutputPath.setObjectName(_fromUtf8("txtOutputPath"))
        self.horizontalLayout_2.addWidget(self.txtOutputPath)
        self.btnBrowseOutputPath = QtGui.QToolButton(self.tabMainOptions)
        self.btnBrowseOutputPath.setObjectName(_fromUtf8("btnBrowseOutputPath"))
        self.horizontalLayout_2.addWidget(self.btnBrowseOutputPath)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.groupBox_2 = QtGui.QGroupBox(self.tabMainOptions)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmbOutputPathStructure = QtGui.QComboBox(self.groupBox_2)
        self.cmbOutputPathStructure.setEditable(False)
        self.cmbOutputPathStructure.setProperty("currentText", _fromUtf8(""))
        self.cmbOutputPathStructure.setObjectName(_fromUtf8("cmbOutputPathStructure"))
        self.gridLayout.addWidget(self.cmbOutputPathStructure, 0, 0, 1, 4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 3, 1, 1)
        self.btnRemovePattern = QtGui.QPushButton(self.groupBox_2)
        self.btnRemovePattern.setObjectName(_fromUtf8("btnRemovePattern"))
        self.gridLayout.addWidget(self.btnRemovePattern, 1, 2, 1, 1)
        self.btnAddPattern = QtGui.QPushButton(self.groupBox_2)
        self.btnAddPattern.setObjectName(_fromUtf8("btnAddPattern"))
        self.gridLayout.addWidget(self.btnAddPattern, 1, 0, 1, 1)
        self.btnEditPattern = QtGui.QPushButton(self.groupBox_2)
        self.btnEditPattern.setObjectName(_fromUtf8("btnEditPattern"))
        self.gridLayout.addWidget(self.btnEditPattern, 1, 1, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.chkMaxFilesPerFolder = QtGui.QCheckBox(self.tabMainOptions)
        self.chkMaxFilesPerFolder.setObjectName(_fromUtf8("chkMaxFilesPerFolder"))
        self.horizontalLayout_6.addWidget(self.chkMaxFilesPerFolder)
        self.txtMaxFilesPerFolder = QtGui.QSpinBox(self.tabMainOptions)
        self.txtMaxFilesPerFolder.setEnabled(False)
        self.txtMaxFilesPerFolder.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtMaxFilesPerFolder.setMaximum(999999999)
        self.txtMaxFilesPerFolder.setProperty("value", 255)
        self.txtMaxFilesPerFolder.setObjectName(_fromUtf8("txtMaxFilesPerFolder"))
        self.horizontalLayout_6.addWidget(self.txtMaxFilesPerFolder)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.chkCamelCase = QtGui.QCheckBox(self.tabMainOptions)
        self.chkCamelCase.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkCamelCase.setObjectName(_fromUtf8("chkCamelCase"))
        self.verticalLayout_2.addWidget(self.chkCamelCase)
        self.chkShortFilenames = QtGui.QCheckBox(self.tabMainOptions)
        self.chkShortFilenames.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.chkShortFilenames.setObjectName(_fromUtf8("chkShortFilenames"))
        self.verticalLayout_2.addWidget(self.chkShortFilenames)
        self.chkPlacePokFilesIntoPOKESSubfolders = QtGui.QCheckBox(self.tabMainOptions)
        self.chkPlacePokFilesIntoPOKESSubfolders.setChecked(True)
        self.chkPlacePokFilesIntoPOKESSubfolders.setObjectName(_fromUtf8("chkPlacePokFilesIntoPOKESSubfolders"))
        self.verticalLayout_2.addWidget(self.chkPlacePokFilesIntoPOKESSubfolders)
        self.verticalLayout_2.setStretch(0, 2)
        self.tabWidget.addTab(self.tabMainOptions, _fromUtf8(""))
        self.tabFileFiltering = QtGui.QWidget()
        self.tabFileFiltering.setObjectName(_fromUtf8("tabFileFiltering"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabFileFiltering)
        self.verticalLayout.setSpacing(7)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.tabFileFiltering)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.txtFormatPreference = QtGui.QLineEdit(self.tabFileFiltering)
        self.txtFormatPreference.setInputMask(_fromUtf8(""))
        self.txtFormatPreference.setObjectName(_fromUtf8("txtFormatPreference"))
        self.horizontalLayout_3.addWidget(self.txtFormatPreference)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tabFileFiltering)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.txtLanguages = QtGui.QLineEdit(self.tabFileFiltering)
        self.txtLanguages.setInputMask(_fromUtf8(""))
        self.txtLanguages.setObjectName(_fromUtf8("txtLanguages"))
        self.horizontalLayout_4.addWidget(self.txtLanguages)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.tabFileFiltering)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.txtMaxArchiveSize = QtGui.QSpinBox(self.tabFileFiltering)
        self.txtMaxArchiveSize.setMinimum(1)
        self.txtMaxArchiveSize.setMaximum(10000)
        self.txtMaxArchiveSize.setObjectName(_fromUtf8("txtMaxArchiveSize"))
        self.horizontalLayout_8.addWidget(self.txtMaxArchiveSize)
        self.label_5 = QtGui.QLabel(self.tabFileFiltering)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.chkIncludeAlternate = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeAlternate.setObjectName(_fromUtf8("chkIncludeAlternate"))
        self.verticalLayout.addWidget(self.chkIncludeAlternate)
        self.chkIncludeDemos = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeDemos.setChecked(True)
        self.chkIncludeDemos.setObjectName(_fromUtf8("chkIncludeDemos"))
        self.verticalLayout.addWidget(self.chkIncludeDemos)
        self.chkIncludeRereleases = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeRereleases.setChecked(True)
        self.chkIncludeRereleases.setObjectName(_fromUtf8("chkIncludeRereleases"))
        self.verticalLayout.addWidget(self.chkIncludeRereleases)
        self.chkIncludeAlternateFileFormats = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeAlternateFileFormats.setChecked(True)
        self.chkIncludeAlternateFileFormats.setObjectName(_fromUtf8("chkIncludeAlternateFileFormats"))
        self.verticalLayout.addWidget(self.chkIncludeAlternateFileFormats)
        self.chkIncludeHacked = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeHacked.setChecked(True)
        self.chkIncludeHacked.setObjectName(_fromUtf8("chkIncludeHacked"))
        self.verticalLayout.addWidget(self.chkIncludeHacked)
        self.chkIncludeXRated = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeXRated.setChecked(True)
        self.chkIncludeXRated.setObjectName(_fromUtf8("chkIncludeXRated"))
        self.verticalLayout.addWidget(self.chkIncludeXRated)
        self.chkIncludeSupplementaryFiles = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeSupplementaryFiles.setChecked(True)
        self.chkIncludeSupplementaryFiles.setObjectName(_fromUtf8("chkIncludeSupplementaryFiles"))
        self.verticalLayout.addWidget(self.chkIncludeSupplementaryFiles)
        self.chkIncludeUnknownFiles = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkIncludeUnknownFiles.setChecked(True)
        self.chkIncludeUnknownFiles.setTristate(False)
        self.chkIncludeUnknownFiles.setObjectName(_fromUtf8("chkIncludeUnknownFiles"))
        self.verticalLayout.addWidget(self.chkIncludeUnknownFiles)
        self.chkSeparateUnknownFiles = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkSeparateUnknownFiles.setChecked(True)
        self.chkSeparateUnknownFiles.setTristate(False)
        self.chkSeparateUnknownFiles.setObjectName(_fromUtf8("chkSeparateUnknownFiles"))
        self.verticalLayout.addWidget(self.chkSeparateUnknownFiles)
        self.chkRetainFoldersForUnknownFiles = QtGui.QCheckBox(self.tabFileFiltering)
        self.chkRetainFoldersForUnknownFiles.setChecked(False)
        self.chkRetainFoldersForUnknownFiles.setTristate(False)
        self.chkRetainFoldersForUnknownFiles.setObjectName(_fromUtf8("chkRetainFoldersForUnknownFiles"))
        self.verticalLayout.addWidget(self.chkRetainFoldersForUnknownFiles)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(13, 1)
        self.tabWidget.addTab(self.tabFileFiltering, _fromUtf8(""))
        self.tabAbout = QtGui.QWidget()
        self.tabAbout.setObjectName(_fromUtf8("tabAbout"))
        self.textBrowser = QtGui.QTextBrowser(self.tabAbout)
        self.textBrowser.setGeometry(QtCore.QRect(20, 10, 441, 331))
        self.textBrowser.setStyleSheet(_fromUtf8("background-color: transparent;"))
        self.textBrowser.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setOpenLinks(True)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.btnReadme = QtGui.QPushButton(self.tabAbout)
        self.btnReadme.setGeometry(QtCore.QRect(20, 350, 241, 28))
        self.btnReadme.setObjectName(_fromUtf8("btnReadme"))
        self.btnFacebook = QtGui.QPushButton(self.tabAbout)
        self.btnFacebook.setGeometry(QtCore.QRect(20, 390, 241, 28))
        self.btnFacebook.setObjectName(_fromUtf8("btnFacebook"))
        self.btnSourceForge = QtGui.QPushButton(self.tabAbout)
        self.btnSourceForge.setGeometry(QtCore.QRect(20, 430, 241, 28))
        self.btnSourceForge.setObjectName(_fromUtf8("btnSourceForge"))
        self.tabWidget.addTab(self.tabAbout, _fromUtf8(""))
        self.gridLayout_3.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.lstInputPaths)
        Dialog.setTabOrder(self.lstInputPaths, self.btnAddPath)
        Dialog.setTabOrder(self.btnAddPath, self.btnRemovePaths)
        Dialog.setTabOrder(self.btnRemovePaths, self.chkTraverseSubdirectories)
        Dialog.setTabOrder(self.chkTraverseSubdirectories, self.txtOutputPath)
        Dialog.setTabOrder(self.txtOutputPath, self.btnBrowseOutputPath)
        Dialog.setTabOrder(self.btnBrowseOutputPath, self.cmbOutputPathStructure)
        Dialog.setTabOrder(self.cmbOutputPathStructure, self.btnAddPattern)
        Dialog.setTabOrder(self.btnAddPattern, self.btnEditPattern)
        Dialog.setTabOrder(self.btnEditPattern, self.btnRemovePattern)
        Dialog.setTabOrder(self.btnRemovePattern, self.chkMaxFilesPerFolder)
        Dialog.setTabOrder(self.chkMaxFilesPerFolder, self.txtMaxFilesPerFolder)
        Dialog.setTabOrder(self.txtMaxFilesPerFolder, self.chkCamelCase)
        Dialog.setTabOrder(self.chkCamelCase, self.chkShortFilenames)
        Dialog.setTabOrder(self.chkShortFilenames, self.chkPlacePokFilesIntoPOKESSubfolders)
        Dialog.setTabOrder(self.chkPlacePokFilesIntoPOKESSubfolders, self.btnLoadSettings)
        Dialog.setTabOrder(self.btnLoadSettings, self.btnSaveSettings)
        Dialog.setTabOrder(self.btnSaveSettings, self.btnSortFiles)
        Dialog.setTabOrder(self.btnSortFiles, self.txtFormatPreference)
        Dialog.setTabOrder(self.txtFormatPreference, self.txtLanguages)
        Dialog.setTabOrder(self.txtLanguages, self.chkIncludeAlternate)
        Dialog.setTabOrder(self.chkIncludeAlternate, self.chkIncludeDemos)
        Dialog.setTabOrder(self.chkIncludeDemos, self.chkIncludeRereleases)
        Dialog.setTabOrder(self.chkIncludeRereleases, self.chkIncludeAlternateFileFormats)
        Dialog.setTabOrder(self.chkIncludeAlternateFileFormats, self.chkIncludeHacked)
        Dialog.setTabOrder(self.chkIncludeHacked, self.chkIncludeXRated)
        Dialog.setTabOrder(self.chkIncludeXRated, self.chkIncludeSupplementaryFiles)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "ZX Pokemaster", None))
        self.btnLoadSettings.setText(_translate("Dialog", "Load Settings...", None))
        self.btnSaveSettings.setText(_translate("Dialog", "Save Settings...", None))
        self.btnSortFiles.setText(_translate("Dialog", "Sort files", None))
        self.groupBox.setTitle(_translate("Dialog", "Input paths", None))
        self.btnAddPath.setText(_translate("Dialog", "Add path...", None))
        self.chkTraverseSubdirectories.setText(_translate("Dialog", "Traverse subdirectories", None))
        self.btnRemovePaths.setText(_translate("Dialog", "Remove path", None))
        self.label.setText(_translate("Dialog", "Output path:", None))
        self.btnBrowseOutputPath.setText(_translate("Dialog", "...", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Output path structure pattern", None))
        self.btnRemovePattern.setText(_translate("Dialog", "Remove pattern", None))
        self.btnAddPattern.setText(_translate("Dialog", "Add pattern...", None))
        self.btnEditPattern.setText(_translate("Dialog", "Edit pattern...", None))
        self.chkMaxFilesPerFolder.setText(_translate("Dialog", "Max files per folder:", None))
        self.chkCamelCase.setText(_translate("Dialog", "CamelCaseInsteadOfSpaces", None))
        self.chkShortFilenames.setText(_translate("Dialog", "Use 8.3 naming scheme", None))
        self.chkPlacePokFilesIntoPOKESSubfolders.setText(_translate("Dialog", "Place .POK files into POKES subfolders", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMainOptions), _translate("Dialog", "Main options", None))
        self.label_2.setText(_translate("Dialog", "Formats preference:", None))
        self.txtFormatPreference.setPlaceholderText(_translate("Dialog", "tap,z80,sna,dsk,trd,tzx,img,mgt,rom,scl,slt,szx", None))
        self.label_3.setText(_translate("Dialog", "Languages:", None))
        self.txtLanguages.setPlaceholderText(_translate("Dialog", "en,es,ru,pl,cz,fr,de,nl,hu,cr,pl,sr,sl,sv,no", None))
        self.label_4.setText(_translate("Dialog", "Max archive size to look into:", None))
        self.label_5.setText(_translate("Dialog", "MB", None))
        self.chkIncludeAlternate.setText(_translate("Dialog", "Include alternate files (marked [a] in TOSEC)", None))
        self.chkIncludeDemos.setText(_translate("Dialog", "Include demos (non-full versions of games)", None))
        self.chkIncludeRereleases.setText(_translate("Dialog", "Include re-releases", None))
        self.chkIncludeAlternateFileFormats.setText(_translate("Dialog", "Include alternate file formats (see formats preference order)", None))
        self.chkIncludeHacked.setText(_translate("Dialog", "Include files marked as cracked, hacked or modded", None))
        self.chkIncludeXRated.setToolTip(_translate("Dialog", "18+ games: may contain nudity, pornographic images, extremely obscene language or hate speech", None))
        self.chkIncludeXRated.setText(_translate("Dialog", "Include x-rated games", None))
        self.chkIncludeSupplementaryFiles.setToolTip(_translate("Dialog", "If a ZX Spectrum file has got other files with the same name in the same folder or in a subfolder, include those as well. May be handy tor maps, manuals etc.", None))
        self.chkIncludeSupplementaryFiles.setText(_translate("Dialog", "Include supplementary files (Warning: may be slow!)", None))
        self.chkIncludeUnknownFiles.setText(_translate("Dialog", "Include unknown files", None))
        self.chkSeparateUnknownFiles.setText(_translate("Dialog", "Put unknown files into \"Unknown\" folder", None))
        self.chkRetainFoldersForUnknownFiles.setText(_translate("Dialog", "Retain relative folder structure for unknown files", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFileFiltering), _translate("Dialog", "File filtering", None))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Brought to you by Helga Iliashenko aka Lady Eklipse</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">with the sencere feelings to the ZX Spectrum community.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">For those willing to support ZX Pokemaster, please consider donating:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">BitCoin: </span><a href=\"bitcoin:1KLBSzFYBpmwwkiG9VhXV6Hfd6YVsnF9D9\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">1KLBSzFYBpmwwkiG9VhXV6Hfd6YVsnF9D9</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">LiteCoin: </span><a href=\"litecoin:Laugnn4XqAUEZ8FSvJvLW3n62BuFHhgraT\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">Laugnn4XqAUEZ8FSvJvLW3n62BuFHhgraT</span></a></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Etherium: 0xF60Dc0c3d32b12Ae02A68723Af9133AD1938a178</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Special thanks to:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Anna Soloviova for moral support;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Gerard Sweeney for </span><a href=\"http://www.the-tipshop.co.uk\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">www.the-tipshop.co.uk</span></a><span style=\" font-size:8pt;\">;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Einar Saukas for ZXDB;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Peter Jones for </span><a href=\"https://spectrumcomputing.co.uk\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">spectrumcomputing.co.uk</span></a><span style=\" font-size:8pt;\">;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">D. Kampschulte aka Der Eratosthenes for beta testing;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">blinkydoos for beta testing;</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">The </span><a href=\"https://www.tosecdev.org\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">TOSEC</span></a><span style=\" font-size:8pt;\"> team, especially:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">gorski, maddog, dziuber, duncantwain, mictlantecuhtle, panda and others.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.btnReadme.setText(_translate("Dialog", "View README", None))
        self.btnFacebook.setText(_translate("Dialog", "Visit Facebook tech support group", None))
        self.btnSourceForge.setText(_translate("Dialog", "Check for new version on SourceForge", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAbout), _translate("Dialog", "Help", None))

import res_rc
