# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SorterLauncher.ui'
#
# Created: Thu Jul 20 03:55:24 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(470, 666)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(470, 527))
        Dialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        Dialog.setBaseSize(QtCore.QSize(470, 527))
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/pokemaster.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        Dialog.setSizeGripEnabled(False)
        self.btnSortFiles = QtGui.QPushButton(Dialog)
        self.btnSortFiles.setGeometry(QtCore.QRect(370, 630, 93, 28))
        self.btnSortFiles.setObjectName(_fromUtf8("btnSortFiles"))
        self.txtOutputPath = QtGui.QLineEdit(Dialog)
        self.txtOutputPath.setGeometry(QtCore.QRect(100, 250, 321, 22))
        self.txtOutputPath.setObjectName(_fromUtf8("txtOutputPath"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 250, 81, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 441, 231))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.btnAddPath = QtGui.QPushButton(self.groupBox)
        self.btnAddPath.setGeometry(QtCore.QRect(330, 30, 93, 28))
        self.btnAddPath.setObjectName(_fromUtf8("btnAddPath"))
        self.btnRemovePaths = QtGui.QPushButton(self.groupBox)
        self.btnRemovePaths.setGeometry(QtCore.QRect(330, 70, 93, 28))
        self.btnRemovePaths.setObjectName(_fromUtf8("btnRemovePaths"))
        self.lstInputPaths = QtGui.QListWidget(self.groupBox)
        self.lstInputPaths.setGeometry(QtCore.QRect(10, 20, 311, 171))
        self.lstInputPaths.setObjectName(_fromUtf8("lstInputPaths"))
        self.chkTraverseSubdirectories = QtGui.QCheckBox(self.groupBox)
        self.chkTraverseSubdirectories.setGeometry(QtCore.QRect(10, 200, 300, 20))
        self.chkTraverseSubdirectories.setChecked(True)
        self.chkTraverseSubdirectories.setObjectName(_fromUtf8("chkTraverseSubdirectories"))
        self.chkIncludeAlternate = QtGui.QCheckBox(Dialog)
        self.chkIncludeAlternate.setGeometry(QtCore.QRect(20, 470, 451, 20))
        self.chkIncludeAlternate.setObjectName(_fromUtf8("chkIncludeAlternate"))
        self.chkIncludeRereleases = QtGui.QCheckBox(Dialog)
        self.chkIncludeRereleases.setGeometry(QtCore.QRect(20, 510, 451, 20))
        self.chkIncludeRereleases.setChecked(True)
        self.chkIncludeRereleases.setObjectName(_fromUtf8("chkIncludeRereleases"))
        self.chkIncludeAlternateFileFormats = QtGui.QCheckBox(Dialog)
        self.chkIncludeAlternateFileFormats.setGeometry(QtCore.QRect(20, 530, 451, 20))
        self.chkIncludeAlternateFileFormats.setChecked(True)
        self.chkIncludeAlternateFileFormats.setObjectName(_fromUtf8("chkIncludeAlternateFileFormats"))
        self.chkIncludeHacked = QtGui.QCheckBox(Dialog)
        self.chkIncludeHacked.setGeometry(QtCore.QRect(20, 550, 451, 20))
        self.chkIncludeHacked.setChecked(True)
        self.chkIncludeHacked.setObjectName(_fromUtf8("chkIncludeHacked"))
        self.txtFormatPreference = QtGui.QLineEdit(Dialog)
        self.txtFormatPreference.setGeometry(QtCore.QRect(180, 280, 241, 22))
        self.txtFormatPreference.setInputMask(_fromUtf8(""))
        self.txtFormatPreference.setObjectName(_fromUtf8("txtFormatPreference"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 280, 161, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 320, 441, 101))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.cmbOutputFolderStructure = QtGui.QComboBox(self.groupBox_2)
        self.cmbOutputFolderStructure.setGeometry(QtCore.QRect(10, 30, 421, 22))
        self.cmbOutputFolderStructure.setEditable(False)
        self.cmbOutputFolderStructure.setProperty("currentText", _fromUtf8(""))
        self.cmbOutputFolderStructure.setObjectName(_fromUtf8("cmbOutputFolderStructure"))
        self.btnAddPattern = QtGui.QPushButton(self.groupBox_2)
        self.btnAddPattern.setGeometry(QtCore.QRect(10, 60, 131, 28))
        self.btnAddPattern.setObjectName(_fromUtf8("btnAddPattern"))
        self.btnRemovePattern = QtGui.QPushButton(self.groupBox_2)
        self.btnRemovePattern.setGeometry(QtCore.QRect(140, 60, 131, 28))
        self.btnRemovePattern.setObjectName(_fromUtf8("btnRemovePattern"))
        self.chkPlacePokFilesIntoPOKESSubfolder = QtGui.QCheckBox(Dialog)
        self.chkPlacePokFilesIntoPOKESSubfolder.setGeometry(QtCore.QRect(20, 610, 441, 20))
        self.chkPlacePokFilesIntoPOKESSubfolder.setChecked(True)
        self.chkPlacePokFilesIntoPOKESSubfolder.setObjectName(_fromUtf8("chkPlacePokFilesIntoPOKESSubfolder"))
        self.btnBrowseOutputPath = QtGui.QToolButton(Dialog)
        self.btnBrowseOutputPath.setGeometry(QtCore.QRect(430, 250, 27, 22))
        self.btnBrowseOutputPath.setObjectName(_fromUtf8("btnBrowseOutputPath"))
        self.chkIncludeXRated = QtGui.QCheckBox(Dialog)
        self.chkIncludeXRated.setGeometry(QtCore.QRect(20, 570, 451, 20))
        self.chkIncludeXRated.setChecked(True)
        self.chkIncludeXRated.setObjectName(_fromUtf8("chkIncludeXRated"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 430, 121, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbOutputFolderStructure_2 = QtGui.QComboBox(Dialog)
        self.cmbOutputFolderStructure_2.setGeometry(QtCore.QRect(150, 430, 161, 22))
        self.cmbOutputFolderStructure_2.setEditable(False)
        self.cmbOutputFolderStructure_2.setObjectName(_fromUtf8("cmbOutputFolderStructure_2"))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.cmbOutputFolderStructure_2.addItem(_fromUtf8(""))
        self.btnFormatPreferenceWindow = QtGui.QToolButton(Dialog)
        self.btnFormatPreferenceWindow.setGeometry(QtCore.QRect(430, 280, 27, 22))
        self.btnFormatPreferenceWindow.setObjectName(_fromUtf8("btnFormatPreferenceWindow"))
        self.chkIncludeUnknownFiles = QtGui.QCheckBox(Dialog)
        self.chkIncludeUnknownFiles.setGeometry(QtCore.QRect(20, 590, 451, 20))
        self.chkIncludeUnknownFiles.setChecked(True)
        self.chkIncludeUnknownFiles.setObjectName(_fromUtf8("chkIncludeUnknownFiles"))
        self.chkIncludeDemos = QtGui.QCheckBox(Dialog)
        self.chkIncludeDemos.setGeometry(QtCore.QRect(20, 490, 451, 20))
        self.chkIncludeDemos.setChecked(True)
        self.chkIncludeDemos.setObjectName(_fromUtf8("chkIncludeDemos"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "ZX Pokemaster", None))
        self.btnSortFiles.setText(_translate("Dialog", "Sort files", None))
        self.label.setText(_translate("Dialog", "Output path:", None))
        self.groupBox.setTitle(_translate("Dialog", "Input paths", None))
        self.btnAddPath.setText(_translate("Dialog", "Add path...", None))
        self.btnRemovePaths.setText(_translate("Dialog", "Remove path", None))
        self.chkTraverseSubdirectories.setText(_translate("Dialog", "Traverse subdirectories", None))
        self.chkIncludeAlternate.setText(_translate("Dialog", "Include alternate files (marked [a] in TOSEC)", None))
        self.chkIncludeRereleases.setText(_translate("Dialog", "Include re-releases", None))
        self.chkIncludeAlternateFileFormats.setText(_translate("Dialog", "Include alternate file formats (see formats preference order)", None))
        self.chkIncludeHacked.setText(_translate("Dialog", "Include files marked as cracked, hacked or modded", None))
        self.txtFormatPreference.setPlaceholderText(_translate("Dialog", "tap,z80,sna,dsk,trd,tzx,img,mgt,rom,scl,slt,szx", None))
        self.label_2.setText(_translate("Dialog", "Formats preference order:", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Output folder structure pattern", None))
        self.btnAddPattern.setText(_translate("Dialog", "Add pattern...", None))
        self.btnRemovePattern.setText(_translate("Dialog", "Remove pattern", None))
        self.chkPlacePokFilesIntoPOKESSubfolder.setText(_translate("Dialog", "Place .POK files into POKES subfolder", None))
        self.btnBrowseOutputPath.setText(_translate("Dialog", "...", None))
        self.chkIncludeXRated.setText(_translate("Dialog", "Include x-rated games", None))
        self.label_3.setText(_translate("Dialog", "Preferred language:", None))
        self.cmbOutputFolderStructure_2.setProperty("currentText", _translate("Dialog", "All", None))
        self.cmbOutputFolderStructure_2.setItemText(0, _translate("Dialog", "All", None))
        self.cmbOutputFolderStructure_2.setItemText(1, _translate("Dialog", "English (en)", None))
        self.cmbOutputFolderStructure_2.setItemText(2, _translate("Dialog", "Spanish (es)", None))
        self.cmbOutputFolderStructure_2.setItemText(3, _translate("Dialog", "Russian (ru)", None))
        self.cmbOutputFolderStructure_2.setItemText(4, _translate("Dialog", "Croatian (hr)", None))
        self.cmbOutputFolderStructure_2.setItemText(5, _translate("Dialog", "Czech (cz)", None))
        self.cmbOutputFolderStructure_2.setItemText(6, _translate("Dialog", "Dutch (nl)", None))
        self.cmbOutputFolderStructure_2.setItemText(7, _translate("Dialog", "German (de)", None))
        self.cmbOutputFolderStructure_2.setItemText(8, _translate("Dialog", "French (fr)", None))
        self.cmbOutputFolderStructure_2.setItemText(9, _translate("Dialog", "Hungarian (hu)", None))
        self.cmbOutputFolderStructure_2.setItemText(10, _translate("Dialog", "Norwegian (no)", None))
        self.cmbOutputFolderStructure_2.setItemText(11, _translate("Dialog", "Polish (pl)", None))
        self.cmbOutputFolderStructure_2.setItemText(12, _translate("Dialog", "Serbian (sr)", None))
        self.cmbOutputFolderStructure_2.setItemText(13, _translate("Dialog", "Slovak (sl)", None))
        self.cmbOutputFolderStructure_2.setItemText(14, _translate("Dialog", "Swedish (sv)", None))
        self.btnFormatPreferenceWindow.setText(_translate("Dialog", "...", None))
        self.chkIncludeUnknownFiles.setText(_translate("Dialog", "Include unknown files", None))
        self.chkIncludeDemos.setText(_translate("Dialog", "Include demos (non-full versions of games)", None))

import res_rc
